# Generated by Django 5.2.3 on 2025-06-17 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionrequest',
            name='review_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='review_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_permission_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
